"""criação das tabelas iniciais

Revision ID: 3462494c872f
Revises: dff1efd09699
Create Date: 2025-05-19 15:00:14.054085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3462494c872f'
down_revision: Union[str, None] = 'dff1efd09699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execucoes_id', table_name='execucoes')
    op.drop_table('execucoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('erro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('valor_total_carga', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('placa_cavalo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('placa_carreta_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('placa_carreta_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_origem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_destino', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remetente_nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remetente_cnpj', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remetente_endereco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destinatario_nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destinatario_cnpj', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destinatario_endereco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condutor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpf_condutor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remetente_cadastrado_apisul', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destinatario_cadastrado_apisul', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rotas_cadastradas_apisul', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id_smp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numero_smp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rota_selecionada', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='execucoes_pkey')
    )
    op.create_index('ix_execucoes_id', 'execucoes', ['id'], unique=False)
    # ### end Alembic commands ###
