"""criação da tabela execucoes

Revision ID: eeeaf304d650
Revises: 3462494c872f
Create Date: 2025-05-19 15:03:02.586903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeeaf304d650'
down_revision: Union[str, None] = '3462494c872f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('historico', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('valor_total_carga', sa.Float(), nullable=True),
    sa.Column('placa_cavalo', sa.String(), nullable=True),
    sa.Column('placa_carreta_1', sa.String(), nullable=True),
    sa.Column('placa_carreta_2', sa.String(), nullable=True),
    sa.Column('local_origem', sa.String(), nullable=True),
    sa.Column('local_destino', sa.String(), nullable=True),
    sa.Column('remetente_nome', sa.String(), nullable=True),
    sa.Column('remetente_cnpj', sa.String(), nullable=True),
    sa.Column('remetente_endereco', sa.String(), nullable=True),
    sa.Column('destinatario_nome', sa.String(), nullable=True),
    sa.Column('destinatario_cnpj', sa.String(), nullable=True),
    sa.Column('destinatario_endereco', sa.String(), nullable=True),
    sa.Column('condutor', sa.String(), nullable=True),
    sa.Column('cpf_condutor', sa.String(), nullable=True),
    sa.Column('remetente_cadastrado_apisul', sa.String(), nullable=True),
    sa.Column('destinatario_cadastrado_apisul', sa.String(), nullable=True),
    sa.Column('rotas_cadastradas_apisul', sa.JSON(), nullable=True),
    sa.Column('id_smp', sa.String(), nullable=True),
    sa.Column('numero_smp', sa.String(), nullable=True),
    sa.Column('rota_selecionada', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execucoes_id'), 'execucoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execucoes_id'), table_name='execucoes')
    op.drop_table('execucoes')
    # ### end Alembic commands ###
